blog/urls.py
from django.conf.urls import url

from .views import (
    article_detail, article_list, category_detail, category_list, index, search,
)


urlpatterns = [
    url(r'^article/$', article_list, name='article-list'),
    url(r'^article/(?P<slug>[^/]+)/$', article_detail, name='article-detail'),
    url(r'^category/$', category_list, name='category-list'),
    url(r'^category/(?P<slug>[^/]+)/$', category_detail, name='category-detail'),
    url(r'^search/$', search, name='search'),
    url(r'^$', index, name='index'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, db_index=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:category-detail", kwargs={'slug': self.slug})


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=254)
    slug = models.SlugField(unique=True, db_index=True)
    text = models.TextField()
    publish_datetime = models.DateTimeField()
    is_public = models.BooleanField(default=False)
    category = models.ForeignKey(Category)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:article-detail", kwargs={'slug': self.slug})

blog/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.utils.timezone import now
from django.views.generic import DetailView, ListView

from .models import Article, Category
from .search import Article as SearchArticle


def index(request):
    return redirect(reverse('blog:article-list'))


class ArticleDetailView(DetailView):
    model = Article

    def get_queryset(self):
        qs = super(ArticleDetailView, self).get_queryset()
        qs = qs.select_related('author', 'category')
        if not self.request.user.is_authenticated():
            qs = qs.filter(is_public=True, publish_datetime__lte=now())
        return qs

article_detail = ArticleDetailView.as_view()


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        qs = super(ArticleListView, self).get_queryset()
        qs = qs.select_related('author', 'category')
        if not self.request.user.is_authenticated():
            qs = qs.filter(is_public=True, publish_datetime__lte=now())
        return qs

article_list = ArticleListView.as_view()


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        ctx = super(CategoryDetailView, self).get_context_data(**kwargs)
        articles = self.object.article_set
        if not self.request.user.is_authenticated():
            articles = articles.filter(
                is_public=True, publish_datetime__lte=now()
            )
        ctx['articles'] = articles.all()
        return ctx

category_detail = CategoryDetailView.as_view()


class CategoryListView(ListView):
    model = Category

category_list = CategoryListView.as_view()


def search(request):
    q = request.GET.get('q', '')
    ctx = {'query': q, 'results': []}
    if q:
        search = SearchArticle.search()
        search = search.query(
            'simple_query_string',
            query=q,
            fields=['title', 'text']
        )
        if not request.user.is_authenticated():
            search = search.filter('term', is_public=True)
            search = search.filter('range', publish_datetime={'lte': 'now'})
        ctx['results'] = search.execute()
    return render(request, 'blog/search.html', ctx)

blog/templates/blog/article_detail.html
{% extends "blog/base.html" %}

{% block content %}
<h1><a href="{{ object.get_absolute_url }}">{{ object }}<a></h1>
<p>
    {{ object.author.get_full_name|default:object.author }}
    on {{ object.publish_datetime|date }}
    in <a href="{{ object.category.get_absolute_url }}">{{ object.category }}</a>
    ({{ object.is_public|yesno:"published,unpublished" }})
</p>
{{ object.text|linebreaks }}
{% endblock %}

blog/templates/blog/article_list.html
{% extends "blog/base.html" %}

{% block content %}
{% for object in object_list %}
    <h1><a href="{{ object.get_absolute_url }}">{{ object }}<a></h1>
    <p>
        {{ object.author.get_full_name|default:object.author }}
        on {{ object.publish_datetime|date }}
        in <a href="{{ object.category.get_absolute_url }}">{{ object.category }}</a>
        ({{ object.is_public|yesno:"published,unpublished" }})
    </p>
    {{ object.text|linebreaks }}
{% empty %}
    <p>No articles yet!</p>
{% endfor %}
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Demo</title>
    </head>
    <body>
        <form action="{% url "blog:search" %}" method="GET">
            Search: <input type="search" name="q" value="{{ query }}" />
            <input type="submit" value="Search">
        </form>
        {% block content %}
        {% endblock %}
    </body>
</html>

blog/templates/blog/category_detail.html
{% extends "blog/base.html" %}

{% block content %}
<h1>{{ object }}</h1>
{% for article in articles %}
    <h2><a href="{{ article.get_absolute_url }}">{{ article }}<a></h2>
    <p>
        {{ article.author.get_full_name|default:article.author }}
        on {{ article.publish_datetime|date }}
        in <a href="{{ article.category.get_absolute_url }}">{{ article.category }}</a>
        ({{ article.is_public|yesno:"published,unpublished" }})
    </p>
    {{ article.text|linebreaks }}
{% empty %}
    <p>No articles yet!</p>
{% endfor %}
{% endblock %}

blog/templates/blog/category_list.html
{% extends "blog/base.html" %}

{% block content %}
{% for object in object_list %}
    <li><a href="{% url "blog:category-detail" slug=object.slug %}">{{ object }}</a></li>
{% empty %}
    <p>No categories yet!</p>
{% endfor %}
{% endblock %}

blog/templates/blog/search.html
{% extends "blog/base.html" %}

{% block content %}
{% for object in results %}
    <h2><a href="{{ object.url }}">{{ object }}<a></h2>
    <p>
        {{ object.author }}
        on {{ object.publish_datetime|date }}
        in <a href="{{ object.category_url }}">{{ object.category }}</a>
        ({{ object.is_public|yesno:"published,unpublished" }})
    </p>
    {{ object.text|linebreaks }}
{% empty %}
    <p>No matching results!</p>
{% endfor %}
{% endblock %}